### ISSUE TITLE
The tensorflow support of Byteps releases

### ISSUE THREAD

**Issue by yuxwhkbu** [bytedance/byteps#238]
I think the latest version does not support tensorflow1.14.0/1.15.0 with bugs when running the synthetic benchmarks(correctly compiled). Could you please tell me the last commits that support tensorflow 1.15.0?

**Comment by yuxwhkbu** [comment]
Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: part or all of the requested memory range is already mapped
The bug is this.

**Comment by bobzhuyb** [comment]
What is the latest version you are referring to? We use TF 1.15 all the time... and we recently added support for TF 2.x https://github.com/bytedance/byteps/pull/219

**Comment by ymjiang** [comment]
@yuxwhkbu The latest master should work with TF 1.15, or you can use `pip3 install byteps==0.2.2`. If you still have compilation errors, you can show us the error logs.

**Comment by bobzhuyb** [comment]
Closing due to inactivity.
